/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef AMD_GENOA_PSP_TRANSFER_H
#define AMD_GENOA_PSP_TRANSFER_H

#define TRANSFER_INFO_SIZE		64
#define TIMESTAMP_BUFFER_SIZE		0x200

#endif	/* AMD_GENOA_PSP_TRANSFER_H */
