#**********************************************************************************
#  Copyright (C) 2022 Advanced Micro Devices, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.  IN NO EVENT SHALL
# THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
# **********************************************************************************

# **********************************************************************************
# Pipeline for keeping mirrors up to date
# **********************************************************************************

name: "Coreboot Mirror"

on:
  # Trigger the Coreboot upstream mirroring to downstream on hourly basis
  schedule:
    # Runs daily
    - cron: '0 * * * *'

jobs:
  coreboot_mirror:
    name: coreboot_mirror
    runs-on: [self-hosted, Linux, ci-prod-coreboot-mirror]

    steps:
    - uses: actions/checkout@v2

    - name: Keep downstream coreboot AMD up to dated with upstream mirror
      run: |
        cd /tmp
        rm -rf coreboot/
        su - swjenci
        git clone git@github.com:coreboot/coreboot.git
        cd coreboot
        git branch
        git remote add downstream git@github.com:AMD-OpenSIL/coreboot.git
        git remote -v
        git push -u downstream --all
        git push -f -u downstream --tags
